#!/bin/bash

export PARENT_DIR=`readlink -f .`
BUILD_DIR=`readlink -f .`/build/tools/loki

FSTAB=$1
OUT=$2
DEVICE=$3
DEFCONFIG=$4
SOURCE=$PWD
UPDATER=$OUT/obj/EXECUTABLES/updater_intermediates/updater

LINENUMBER=`sed -n "/\/boot/ =" $FSTAB | head -1`
LINE=`sed -n "${LINENUMBER}p" $FSTAB`
stringarray=(${LINE})
bootpartition=${stringarray[2]}
partition_type=${stringarray[1]}
KERNELVERSION=`sed -n -e "/CONFIG_LOCALVERSION/s/^.*=//p" $4`
SYSTEMNUMBER=`sed -n '/\/system/ =' $FSTAB`
SYSTEMLINE=`sed -n "${SYSTEMNUMBER}p" $FSTAB`
systemarray=(${SYSTEMLINE})
systemtype=${systemarray[1]}
systemmount=${systemarray[2]}

CL_GRN="\033[32m"
CL_RST="\033[0m"

rm -r $OUT/*kernel*

if [ ! -f "$UPDATER" ]
then
    make updater &>> /dev/null
fi
if [ ! -f "${ANDROID_HOST_OUT}/framework/signapk.jar" ]
then
    make signapk &>> /dev/null
fi

if [ "$KERNELVERSION" != "" ]
then
    VERSION=`echo $KERNELVERSION | cut -d '-' -f2 | cut -d '"' -f1`
    KERNEL_VERSION=$VERSION-kernel
else
    KERNEL_VERSION=Gummy-$DEVICE-kernel-$(date +"%m-%d-%y")
fi
#rm $OUT/$KERNEL_VERSION
ZIP_DIR=$OUT/$KERNEL_VERSION
mkdir $ZIP_DIR

# Make the updater-script
UPDATER_DIR=$ZIP_DIR/META-INF/com/google/android
mkdir -p $UPDATER_DIR
cp $OUT/obj/EXECUTABLES/updater_intermediates/updater $UPDATER_DIR/update-binary
cp $BUILD_DIR/updater-script $UPDATER_DIR/updater-script
mkdir -p $ZIP_DIR/system/bin
cp $BUILD_DIR/loki.sh $ZIP_DIR/system/bin/loki.sh

# Copy the kernel and libs
cp $OUT/boot.img $ZIP_DIR/boot.img
mkdir -p $ZIP_DIR/system/lib/modules
cp -r $OUT/system/lib/modules/* $ZIP_DIR/system/lib/modules

#zip package
cd $ZIP_DIR
zip -qr ../$KERNEL_VERSION.zip ./
cd $OUT
rm -rf $ZIP_DIR

#sign package
java -jar ${ANDROID_HOST_OUT}/framework/signapk.jar ${SOURCE}/build/target/product/security/testkey.x509.pem ${SOURCE}/build/target/product/security/testkey.pk8 $KERNEL_VERSION.zip $KERNEL_VERSION-signed.zip
rm ./$KERNEL_VERSION.zip
echo -e ${CL_GRN}"Loki!"${CL_RST}
md5sum $KERNEL_VERSION-signed.zip
cd $SOURCE
